# news_lk3.custom_newspapers.fallback (auto generated)
# flake8: noqa: F401

from news_lk3.custom_newspapers.fallback.ArmyLk import ArmyLk
from news_lk3.custom_newspapers.fallback.EnglishLankaviewsCom import EnglishLankaviewsCom
from news_lk3.custom_newspapers.fallback.EuthayanCom import EuthayanCom
from news_lk3.custom_newspapers.fallback.LankasrinewsCom import LankasrinewsCom
from news_lk3.custom_newspapers.fallback.LmdLk import LmdLk
from news_lk3.custom_newspapers.fallback.MawbimaLk import MawbimaLk
from news_lk3.custom_newspapers.fallback.NeruppuCom import NeruppuCom
from news_lk3.custom_newspapers.fallback.NewsradioLk import NewsradioLk
from news_lk3.custom_newspapers.fallback.RedfmLk import RedfmLk
from news_lk3.custom_newspapers.fallback.RiviraLk import RiviraLk
from news_lk3.custom_newspapers.fallback.RupavahiniLk import RupavahiniLk
from news_lk3.custom_newspapers.fallback.SannasaNet import SannasaNet
from news_lk3.custom_newspapers.fallback.SarasaviyaLk import SarasaviyaLk
from news_lk3.custom_newspapers.fallback.SathhandaLk import SathhandaLk
from news_lk3.custom_newspapers.fallback.SithafmLk import SithafmLk
from news_lk3.custom_newspapers.fallback.SiyathafmLk import SiyathafmLk
from news_lk3.custom_newspapers.fallback.SlbcLk import SlbcLk
from news_lk3.custom_newspapers.fallback.SlguardianOrg import SlguardianOrg
from news_lk3.custom_newspapers.fallback.SooriyanfmLk import SooriyanfmLk
from news_lk3.custom_newspapers.fallback.SrilankamirrorCom import SrilankamirrorCom
from news_lk3.custom_newspapers.fallback.TheleaderLk import TheleaderLk
from news_lk3.custom_newspapers.fallback.ThemorningLk import ThemorningLk
from news_lk3.custom_newspapers.fallback.TheneeCom import TheneeCom
from news_lk3.custom_newspapers.fallback.ThesamnetCoUk import ThesamnetCoUk
from news_lk3.custom_newspapers.fallback.ThinakaranLk import ThinakaranLk
from news_lk3.custom_newspapers.fallback.ThinakkuralLk import ThinakkuralLk
from news_lk3.custom_newspapers.fallback.TnlrocksCom import TnlrocksCom
from news_lk3.custom_newspapers.fallback.VfmLk import VfmLk
from news_lk3.custom_newspapers.fallback.VikalpaOrg import VikalpaOrg
from news_lk3.custom_newspapers.fallback.VimasumaCom import VimasumaCom
from news_lk3.custom_newspapers.fallback.VivalankaCom import VivalankaCom
from news_lk3.custom_newspapers.fallback.YesfmonlineCom import YesfmonlineCom
from news_lk3.custom_newspapers.fallback.YfmLk import YfmLk
